version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: jennchain
      POSTGRES_PASSWORD: jennchain
      POSTGRES_DB: jennchain
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development

volumes:
  db_data:
    driver: local
